Zalidane.com/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zalidane.com.Models;

namespace ZalidaneSite.Controllers
{
    public class ImageController : Controller
    {
        /*
        public FileContentResult ShowThumbnail(int id)
        {
            var thumbnailData = GrabImage(id, "thumbnail");

            return File(thumbnailData, "image/jpg");
        }

        public FileContentResult ShowImage(int id)
        {
            var imageData = GrabImage(id, "image");
            return File(imageData, "image/jpg");
        }

        private byte[] GrabImage(int id, string image)
        {
            //ZalidaneBlogConnection db = new ZalidaneBlogConnection();
            CodeSample codeSample = db.CodeSamples.Find(id);

            byte[] imageData;

            switch (image)
            {
                case "thumbnail":
                    imageData = codeSample.Thumbnail;
                    break;
                case "image":
                    imageData = codeSample.Image;
                    break;
                default:
                    imageData = new byte[] { };
                    break;
            }

            return imageData;
        }
        */
    }
}

Zalidane.com/Controllers/SamplesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Zalidane.com.Models;

namespace ZalidaneSite.Controllers
{
    public class SamplesController : Controller
    {
        //private ZalidaneBlogConnection db = new ZalidaneBlogConnection();
        private ZalidaneBlogModel db = new ZalidaneBlogModel();

        // GET: Samples
        public ActionResult Index()
        {
            List<CodeSample> codeSamples = null;
            codeSamples = db.CodeSamples.ToList();

            if (codeSamples == null)
            {
                codeSamples = new List<CodeSample>();
            }

            return View(codeSamples);
        }

        // GET: Samples/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CodeSample codeSample = db.CodeSamples.Find(id);
            if (codeSample == null)
            {
                return HttpNotFound();
            }
            return View(codeSample);
        }

        // GET: Samples/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Samples/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Description,Url,Thumbnail,Image")] CodeSample codeSample, HttpPostedFileBase thumbnailUpload, HttpPostedFileBase imageUpload)
        {
            if (ModelState.IsValid)
            {
                /*
                if (thumbnailUpload != null && thumbnailUpload.ContentLength > 0)
                {
                    using (var reader = new BinaryReader(thumbnailUpload.InputStream))
                    {
                        codeSample.Thumbnail = reader.ReadBytes(thumbnailUpload.ContentLength);
                    }
                }

                if (imageUpload != null && imageUpload.ContentLength > 0)
                {
                    using (var reader = new BinaryReader(imageUpload.InputStream))
                    {
                        codeSample.Image = reader.ReadBytes(imageUpload.ContentLength);
                    }
                }
                */

                string message = "";
                try
                {
                    db.CodeSamples.Add(codeSample);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException dbe)
                {
                    foreach (var eve in dbe.EntityValidationErrors)
                    {
                        string msg = String.Format("Entity of Type {0} in state {1} has the following validation errors:\n\r",
                                                    eve.Entry.Entity.GetType().Name, eve.Entry.State);

                        foreach (var ve in eve.ValidationErrors)
                        {
                            msg += String.Format("- Property: {0}, Error: {1}\n\r", ve.PropertyName, ve.ErrorMessage);
                        }

                        message += msg;
                    }

                    return View("Error", message);
                }

            }

            return View(codeSample);
        }

        // GET: Samples/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CodeSample codeSample = db.CodeSamples.Find(id);
            if (codeSample == null)
            {
                return HttpNotFound();
            }
            return View(codeSample);
        }

        // POST: Samples/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Description,Url,Thumbnail,Image")] CodeSample codeSample, HttpPostedFileBase thumbnailUpload, HttpPostedFileBase imageUpload)
        {
            if (ModelState.IsValid)
            {
                /*
                if (thumbnailUpload != null && thumbnailUpload.ContentLength > 0)
                {
                    using (var reader = new BinaryReader(thumbnailUpload.InputStream))
                    {
                        codeSample.Thumbnail = reader.ReadBytes(thumbnailUpload.ContentLength);
                    }
                }

                if (imageUpload != null && imageUpload.ContentLength > 0)
                {
                    using (var reader = new BinaryReader(imageUpload.InputStream))
                    {
                        codeSample.Image = reader.ReadBytes(imageUpload.ContentLength);
                    }
                }
                */

                string message = "";
                try
                {
                    db.Entry(codeSample).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException dbe)
                {
                    foreach (var eve in dbe.EntityValidationErrors)
                    {
                        string msg = String.Format("Entity of Type {0} in state {1} has the following validation errors:\n\r",
                                                    eve.Entry.Entity.GetType().Name, eve.Entry.State);

                        foreach (var ve in eve.ValidationErrors)
                        {
                            msg += String.Format("- Property: {0}, Error: {1}\n\r", ve.PropertyName, ve.ErrorMessage);
                        }

                        message += msg;
                    }

                    return View("Error", message);
                }
            }
            return View(codeSample);
        }

        // GET: Samples/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CodeSample codeSample = db.CodeSamples.Find(id);
            if (codeSample == null)
            {
                return HttpNotFound();
            }
            return View(codeSample);
        }

        // POST: Samples/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CodeSample codeSample = db.CodeSamples.Find(id);
            db.CodeSamples.Remove(codeSample);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Zalidane.com/Views/Samples/Create.cshtml
@model Zalidane.com.Models.CodeSample

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Samples", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CodeSample</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thumbnail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="thumbnail" name="thumbnailUpload" class="form-control" />
                @*@Html.EditorFor(model => model.Thumbnail, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Thumbnail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="image" name="imageUpload" class="form-control" />
                @*@Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Zalidane.com/Views/Samples/Delete.cshtml
@model Zalidane.com.Models.CodeSample

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CodeSample</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thumbnail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thumbnail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Zalidane.com/Views/Samples/Details.cshtml
@model Zalidane.com.Models.CodeSample

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CodeSample</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thumbnail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thumbnail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Zalidane.com/Views/Samples/Edit.cshtml
@model Zalidane.com.Models.CodeSample

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CodeSample</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thumbnail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Action("ShowThumbnail", "Image", new { id = Model.Id })" />
                <input type="file" id="thumbnail" name="thumbnailUpload" class="form-control" />
                @Html.ValidationMessageFor(model => model.Thumbnail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Action("ShowImage", "Image", new { id = Model.Id })" />
                <input type="file" id="image" name="imageUpload" class="form-control" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Zalidane.com/Views/Samples/Index.cshtml
@model IEnumerable<Zalidane.com.Models.CodeSample>

@{
    ViewBag.Title = "Samples";
}

<div id="mainImage" class="jumbotron">
    <h1><span class="bg-success img-rounded">&nbsp;Sample Projects&nbsp;</span></h1>
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div id="codeSamples">
    @foreach (var item in Model)
    {
        <hr />

        <div class="panel">
            <div class="row">
                <div class="col-md-8">
                    <h2 class="panel-heading">@item.Title <small><a href="@item.Url"> on GitHub</a></small></h2>
                </div>
                <div class="col-md-1"></div>
                <div class="col-md-3 text-right">
                    <span>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </span>
                </div>
            </div>

            <hr />
            <div class="row panel-body">
                <div class="col-md-5" data-toggle="modal" data-target="#@("modal"+item.Id)">
                    <img src="@Url.Action("ShowImage", "Image", new { id = item.Id })" />
                </div>
                <div class="col-md-2"></div>
                <div class="col-md-5">
                    <h3>Project Description</h3>
                    <p>@item.Description</p>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="@("modal"+item.Id)" tabindex="-1" role="dialog" aria-labelledby="@("modal"+item.Id+"Label")" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <img src="@Url.Action("ShowImage", "Image", new { id = item.Id })" />
                </div>
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    function getElement(id) {
        if (document.getElementById) {
            return document.getElementById(id);
        } else if (document.all) {
            return document.all[id];
        } else if (document.layers) {
            return document.layers[id];
        } else {
            return null;
        }
    }

    function ShowPanel(panelId) {
        var panel = getElement(panelId + "Section");
        panel.className = panel.className.replace('hidden', 'visible');
    }

    function HidePanel(panelId) {
        var panel = getElement(panelId + "Section");
        panel.className = panel.className.replace('visible', 'hidden');
    }
</script>