Zalidane.com/Models/Post.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zalidane.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Comments = new HashSet<Comment>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Body { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}

Zalidane.com/Controllers/WeblogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zalidane.com.Models;
using PagedList;
using System.Net;
using System.Data.Entity.Core;
using System.Text;

namespace ZalidaneSite.Controllers
{
    public class WeblogController : Controller
    {
        #region Private Properties
        
        //private ZalidaneBlogConnection db = new ZalidaneBlogConnection();
        private ZalidaneBlogModel db = new ZalidaneBlogModel();

        // TODO: Don't just return true

        public bool IsAdmin { get { return true; /* return Session["IsAdmin"] != null && (bool)Session["IsAdmin"]; */ } }
        #endregion

        public ViewResult Index(int? page)
        {
            List<Post> Posts = null;
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var posts = from p in db.Posts select p;

            Posts = posts.OrderByDescending(p => p.DateTime).ToList();

            if (Posts == null)
            {
                Posts = new List<Post>();
                Posts.Add(CreatePost());
            }

            return View(Posts.ToPagedList(pageNumber, pageSize));
        }

        [ValidateInput(false)]
        public ActionResult Update(int? id, string title, string body, DateTime dateTime, string tags)
        {
            if (!IsAdmin)
            {
                RedirectToAction("Index");
            }

            Post post = GetPost(id);
            post.Title = title;
            post.Body = body;
            post.DateTime = dateTime;
            post.Tags.Clear();

            tags = tags ?? string.Empty;
            string[] tagNames = tags.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);

            foreach (string tagName in tagNames)
            {
                post.Tags.Add(GetTag(tagName));
            }

            if (!id.HasValue)
            {
                db.Posts.Add(post);
            }
            db.SaveChanges();

            return RedirectToAction("Post", new { id = post.ID });
        }
        
        public ActionResult Edit(int? id)
        {
            Post post = GetPost(id);
            StringBuilder tagList = new StringBuilder();
            foreach (Tag tag in post.Tags)
            {
                tagList.AppendFormat("{0} ", tag.Name);
            }
            ViewBag.Tags = tagList.ToString();

            return View(post);
        }
        
        public ActionResult Post(int? id)
        {
            Post post = null;

            if (id.HasValue)
            {
                post = db.Posts.Where(p => p.ID == id).FirstOrDefault();

                if (post == null)
                {
                    post = CreatePost();
                }
            }

            return View(post);
        }

        #region Helper Methods

        private Tag GetTag(string tagName)
        {
            return db.Tags.Where(tag => tag.Name == tagName).FirstOrDefault() ?? new Tag() { Name = tagName };
        }

        private Post GetPost(int? id)
        {
            return id.HasValue ? db.Posts.Where(post => post.ID == id).First() : new Post() { ID = -1 };
        }

        private Post CreatePost()
        {
            Post post = new Post
            {
                ID = 0,
                Title = "Temporary Post",
                Body = "If you are seeing this text, the database is unavailable.  Please try again later.",
                Comments = new List<Comment>
                 {
                     new Comment
                     { 
                         ID=0, 
                         Body="This is a test comment", 
                         DateTime=DateTime.Today, 
                         Email="admin@zalidane.com", 
                         Name="Zalidane", 
                         PostID=0
                     }
                 },
                DateTime = DateTime.Today,
                Tags = null
            };

            return post;
        }

        #endregion
    }
}

Zalidane.com/Views/Weblog/Edit.cshtml
@model Zalidane.com.Models.Post

@{
    ViewBag.Title = "Edit";
    
    DateTime dateTime = Model.DateTime.Year > 2000 ? Model.DateTime : DateTime.Now;
}

<h2>Edit</h2>


@using (Html.BeginForm("Update", "Weblog", FormMethod.Post, new { id = "postForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if (Model.ID != -1)
        {
            //Html.HiddenFor(model => model.ID, new { name = "id" });
            <input type="hidden" name="id" value="@Model.ID" />
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", name = "title" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="dateTime" value="@dateTime" class="form-control" />
                @*@Html.EditorFor(model => model.DateTime, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.DateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model=>model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" name="tags" value="@ViewBag.Tags" class="form-control" />
                @Html.ValidationMessageFor(model=>model.Tags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="body" rows="10" cols="80" class="form-control">@Model.Body</textarea>
                @*@Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Zalidane.com/Views/Weblog/Index.cshtml
@using Zalidane.com.Helpers;
@model PagedList.IPagedList<Zalidane.com.Models.Post>
@using PagedList.Mvc

<link rel="stylesheet" href="~/Content/PagedList.css" type="text/css" />

@{
    ViewBag.Title = "Blog";
    var author = "@Zalidane";
}

<div id="mainImage" class="jumbotron">
    <h1><span class="bg-success img-rounded">&nbsp;My Blog&nbsp;</span></h1>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="row">
                @foreach (var post in Model)
                {
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-md-4 pull-left">
                                    <a href="~/Weblog/Post/@post.ID">@Html.DisplayFor(modelItem => post.Title)</a>
                                </div>
                                <div class="col-md-offset-8 small text-right">
                                    <small>@(post.DateTime.ToLongDateString())&nbsp;</small>
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
                            @if (post.Body.Length > 200)
                            {
                                <span>@(Html.Raw(post.Body.Substring(0, 200) + "</p>"))...</span>
                                <a class="btn btn-xs btn-default" href="~/Weblog/Post/@post.ID">Read More &raquo;</a>
                                <br />
                            }
                            else
                            {
                                <span>@Html.Raw(post.Body)...</span>
                            }
                        </div>
                        <div class="panel-footer">
                            <!-- social links -->
                            <div class="row">
                                <div class="col-md-1">
                                    <div class="fb-like" data-href="http://zalidane.com/Weblog/Post/@post.ID" data-layout="button" data-action="like"
                                         data-show-faces="true" data-share="false"></div>
                                </div>
                                <div class="col-md-1">
                                    @*<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://zalidane.com/Weblog/Post/@post.ID"
                                        data-text="@post.Title" data-via="zalidane" data-count="none">Tweet</a>*@
                                    <a class="twitter-share-button popup" href="https://twitter.com/share?text=@post.Title">Tweet</a>
                                </div>
                                <div class="col-md-1">
                                </div>
                                <div class="col-md-7">
                                    @foreach (string tag in TagHelper.GetTags(post))
                                    {
                                        string separator = "|";
                                        <a href="~/Weblog/Tag/@tag"> @tag</a> @separator
                                    }
                                </div>
                                <div class="col-md-2 text-right">
                                    <span>Comments: @Html.DisplayFor(modelItem => post.Comments.Count)&nbsp;</span>
                                </div>
                            </div>
                            <!-- end social links -->
                        </div>
                    </div>
                }
            </div>
        </div>

        @*<div class="col-md-1"></div>*@

        <!-- Twitter feed -->
        <div class="col-md-4">
            <a class="twitter-timeline" href="https://twitter.com/zalidane" data-widget-id="480102181656219648">Tweets by @author</a>
            <script>
                !function (d, s, id) {
                    var js, fjs = d.getElementsByTagName(s)[0],
                        p = /^http:/.test(d.location) ? 'http' : 'https';
                    if (!d.getElementById(id)) {
                        js = d.createElement(s);
                        js.id = id;
                        js.src = p + "://platform.twitter.com/widgets.js";
                        fjs.parentNode.insertBefore(js, fjs);
                    }
                }(document, "script", "twitter-wjs");
            </script>
        </div>
        <!-- end Twitter feed -->
    </div>
</div>
@*for each post, display the title, date, tags, and link to the comments*@

<br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

    <div id="fb-root"></div>
    <script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

Zalidane.com/Views/Weblog/Post.cshtml
@model Zalidane.com.Models.Post

@{
    ViewBag.Title = "Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
    bool isAdmin = ViewBag.IsAdmin ?? false;
}

<img class="jumbotron" src="http://placehold.it/1024x300" />

<h2>@Html.DisplayFor(model => model.Title)</h2>
<h5>

    @if (Model != null)
    {
    @Model.DateTime.ToLongDateString()
    }
    else
    {
    @DateTime.Today.ToLongDateString();
    }

</h5>

<div>
    <hr />
    @if (Model != null)
    {
        @Html.Raw(Model.Body)
    }
    else
    {
        <p>No Post to show, please <a href="~/Weblog/Index">try again</a>.</p>
    }
    <hr />

</div>
<p>
    @if (isAdmin)
    {
        Html.ActionLink("Edit", "Edit", new { id = Model.ID }); <span> | </span>
    }

    @Html.ActionLink("Back to List", "Index")
</p>